version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  mail-dev:
    container_name: mail-dev-barbershop
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"